### ISSUE TITLE
undefined info in header

### ISSUE THREAD

**Issue by wdecoster** [eldariont/svim#10]
Me again :)

bcftools complains:

```
[W::vcf_parse] INFO 'STD_SPAN' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'STD_POS' is not defined in the header, assuming Type=String
```

Cheers,
W

**Comment by eldariont** [comment]
Hi, I fixed this with 3897f447d928764ef329b73520942582c38ce794 two weeks ago but you probably use the conda version of svim which is more than a month old. I just drafted a new release which should update the conda recipe soon.

**Comment by wdecoster** [comment]
Yes indeed, I was using the conda version. Thanks!

**Comment by wdecoster** [comment]
I just merged the new version: https://github.com/bioconda/bioconda-recipes/pull/13599

**Comment by eldariont** [comment]
Thanks, Wouter! :) When I last checked yesterday the tests were still running.

**Comment by wdecoster** [comment]
Yes, there were some issues with the MacOS build testing - so these had to be restarted and are now finishing.

**Comment by rl4940** [comment]
@eldariont @wdecoster 
Hi all, I downloaded the v2.0.0 version, but still suffering the same question here, idk what's going on.

**Comment by rl4940** [comment]
I checked the file SVIM_COMBINED.py and these lines do exist, kinda weired
