### ISSUE TITLE
ModuleNotFoundError: No module named 'svim'

### ISSUE THREAD

**Issue by niccw** [eldariont/svim#17]
HI,

I installed svim using pip but cannot make it work.

**Comment by niccw** [comment]
fixed by using virtualenv

**Comment by eldariont** [comment]
Hi Nicola,

thanks for reporting the issue you had. Because you gave little information I cannot say what went wrong precisely but it seems as if you could fix the problem in the meantime. Therefore, I will close this now.

Cheers
David
