### ISSUE TITLE
Can the software detecting cnvs, differing from the dup.tandom and dup.interspered?

### ISSUE THREAD

**Issue by forrwill** [eldariont/svim#18]
hello,
      the software seems to be rewrited by python script, and the before version can detecting cnvs from small genomes，and I want to know whether  the newest version can detect cnvs or not? and which option control the genotypes in the final vcfs, thank you!

**Comment by eldariont** [comment]
Hi Will,

thanks for your questions.
> the software seems to be rewrited by python script, and the before version can detecting cnvs from small genomes

Which previous version of svim do you mean that can detect CNVs from small genomes? Can you give me the concrete version you are referring to?

> and I want to know whether the newest version can detect cnvs or not?

There are different types of CNVs, mainly deletions (where the copy number decreases) and duplications (where the copy number increases). Both types can be detected by svim. Are there types of CNVs other than these that you have in mind?

> and which option control the genotypes in the final vcfs

I'm not sure what you mean exactly with this question. There are several parameters that you can tune to control how svim makes genotype calls. Just type `svim alignment -h` and look for a section called `GENOTYPE`.

Cheers
David

**Comment by forrwill** [comment]
HI, eldariont 
     I tested the software with Sequel reads, and I get the vcf file, but genotype infotmation is not contained, it seems that something was wrong, 
![图片](https://user-images.githubusercontent.com/41096851/62991542-9a951c00-be82-11e9-91ac-140b392614a1.png)
and the command line is like this:
svim reads osa1 osa1.fq.fn  osa.fasta  --insertion_sequences --aligner minimap2 --sample osa1 --sequence_alleles

**Comment by eldariont** [comment]
Hi Will,

what is the mean genome coverage of your read set? Variants with a score below 3, i.e. variants supported by only 1 or 2 reads (see `--minimum_score` parameter) are not assigned a genotype because that would be very imprecise.

David

**Comment by forrwill** [comment]
thank you! I miss it, I select two bams for the software testing, and It might be the reason!
thank you very much!

**Comment by eldariont** [comment]
Good to hear that you found the problem. I will close this issue now but feel free to reopen it if the problem persists.
