### ISSUE TITLE
Problem with installing through conda

### ISSUE THREAD

**Issue by SHuang-Broad** [eldariont/svim#19]
Hi, 

I'm about to test out this tool via

`conda install -c bioconda svim`

but received the following errors.
Can you help me please?
Thank you!

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package biopython conflicts for:
svim -> biopython
Package ca-certificates conflicts for:
svim -> python=3.6 -> openssl=1.0 -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1c,<1.1.2a'] -> ca-certificates
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
Package pip conflicts for:
svim -> python=3.6 -> pip
python=3.7 -> pip
Package wheel conflicts for:
svim -> python=3.6 -> pip -> wheel
python=3.7 -> pip -> wheel
Package setuptools conflicts for:
svim -> matplotlib -> setuptools
python=3.7 -> pip -> setuptools
Package python-dateutil conflicts for:
svim -> matplotlib -> python-dateutil
Package python conflicts for:
python=3.7
```

**Comment by eldariont** [comment]
Hi Steve,

I'm sorry to hear you're having problems installing svim. conda packages with all their dependencies can be very tricky sometimes. My guess is that you are installing svim into the conda base environment where it causes a conflict with some other already installed packages. It seems as if some packages require python 3.7 while svim requires python 3.6.

You could try installing svim into a separate environment with `conda create -n svim_env svim`. This will create the new environment "svim_env" and installs only svim + its dependencies into it. After you activate the new environment with `conda activate svim_env` you can run svim with `svim --help`.

Please let me know if that solves the issue.
Best
David

**Comment by eldariont** [comment]
Hi Steve,
I'm closing this issue now but feel free to reopen if the problem persists.
David

**Comment by SHuang-Broad** [comment]
Hi David,

I apologize that it took me sooooooo long to get back to you.
Yes, the conflict, like you said, is due to the version of python (3.7 vs 3.6).
Is there a reason for using python 3.6 as opposed to 3.7?

In the meantime, is it possible to publish an "official" docker for SVIM?
I've build one for my own experiments, but it would be better if there's an official one.
(Let me know if you want to see my Dockerfile).

Thanks!
Steve

**Comment by eldariont** [comment]
Hi Steve,

good to hear that you were able to fix the problem. There is no real reason for using python 3.6 instead of 3.7. I can definitely update to 3.7 with the next release.

There were a few reasons for not publishing a docker container for SVIM. Firstly, docker requires root permissions to run which makes it impossible to run in many environments (including at our institute). Secondly, I would like to keep maintenance of SVIM minimal and don't want to update three channels (pypi, conda and docker) for a single release. Thirdly, svim is usually quite simple to install using python, pip or conda. Feel free, however, to publish your own docker container for SVIM :)

Best
David

**Comment by SHuang-Broad** [comment]
I understand better now. Thanks for the explanation, David!

We rely heavily on cloud-based computing and pipelining, where a docker is necessary for running essentially all informatics tools.
We published our Dockerfile for building the SVIM docker here, which in case you find useful can always be copied:

https://github.com/broadinstitute/long-read-pipelines/blob/master/docker/lr-svim/Dockerfile

**Comment by eldariont** [comment]
Great, thanks for sharing!
