### ISSUE TITLE
issue when reading sam/bam of empty SEQ field

### ISSUE THREAD

**Issue by xp3i4** [eldariont/svim#21]
SVIM works fine in most cases.
But I'm wondering is it possible to run with bam of empty SEQ field (the 10th column in the SAM format).
Currently it prompts the following for such bam, which seems to call the sequence bases.
`SVIM_intra.py", line 42, in analyze_alignment_indel
    insertion_seq = alignment.query_sequence[pos_read:pos_read+length]
TypeError: 'NoneType' object is not subscriptable`
But since the final result doesn't contain information regarding the SEQ filed, I think it would be  more flexible to use if it can run sam/bam with limited information (such as the cigar only).

**Comment by eldariont** [comment]
Hi Chenxu,

sorry for the delay. I now committed a fix that makes svim work on BAM files with empty SEQ fields. By the way, the `--insertion_sequences` option enables the output of insertion sequences from the supporting reads. That's where the SEQ field is used and required. Without this option, the SEQ field is ignored.

Cheers
David

**Comment by xp3i4** [comment]
Hi David,

Thank you for your commit.
Pleased to learn that the handy caller works well in these cases now.

all the best,
Chenxu
