### ISSUE TITLE
Q: is it possible to allow users choose between NGMLR Minimap2?

### ISSUE THREAD

**Issue by SHuang-Broad** [eldariont/svim#22]
Hi David,

I am reading the Wiki page and found that NGLMR is a required dependency in addition to minimap2.
Now since minimap2 also does alignment, I'd say it makes sense to give the users an option to use minimap2 for mapping and alignment as well, therefore having one less dependency.

Of course, this is totally dependent on the assumptions that
  * SVIM doesn't depend on custom NGLMR tags in critical ways and
  * the two aligners don't give results so different that affect the performance of SVIM

What do you think?

Steve

**Comment by SHuang-Broad** [comment]
closing as I read and understand better.

**Comment by eldariont** [comment]
Hi Steve,

apologies for my late reply. I have been out of office for two weeks.
As you might have discovered by now, SVIM has the option `--aligner` that lets you choose which aligner to use (ngmlr or minimap2). To offer this choice, both aligners are dependencies of SVIM. SVIM does not depend on custom ngmlr tags in any way so it works in a similar fashion on both kinds of input. Nevertheless, both aligners have their own peculiarities that might affect the performance of SVIM so it's always worth trying out both of them.

Please let me know if you think I could improve the wiki to avoid confusion for other users and make it as intuitive as possible.

All the best
David

**Comment by SHuang-Broad** [comment]
Thanks for the answer, David.

I realized that SVIM has the alignment module incorporated, which is not typically what SV callers do (analysis-ready BAMs are usually assumed) but I can understand why you included that.

I'll get back to you once we do our analysis on the SVIM callset.
The plots definitely look interesting!

Steve

**Comment by eldariont** [comment]
Yes, you're right that this is not typical for SV callers. However, SVIM can process analysis-ready BAMs using `svim alignment ..`. Additionally. ngmlr and minimap2 are not strict dependencies, i.e. it is possible to install svim via pip or python without them. In that case, only BAM files can be processed and the `svim reads` mode won't work.
