### ISSUE TITLE
complex events detection

### ISSUE THREAD

**Issue by jiadong324** [eldariont/svim#25]
Hi,

I try to use Sniffle and SVIM search for complex SVs, I am wondering if there any recommended parameter settings for CCS reads.

Thanks!

**Comment by eldariont** [comment]
Hi Darren,

thanks for your question. In my experiments with CCS data, the default parameters worked very well and no particular settings were needed. CCS reads are just cleaner than CLR reads which will lead to considerably better results.

Best
David

**Comment by eldariont** [comment]
Concerning complex SVs: SVIM has not been designed for complex SVs (such as inverted duplications or other complex rearrangements). It detects simple events, such as deletions, insertions and inversions and also outputs breakends from split alignments. You can of course always parse and analyze these breakends yourself. Please let me know if you have more questions.

**Comment by jiadong324** [comment]
@eldariont 

Thanks for your feedbacks!
