### ISSUE TITLE
Understanding the scoring?

### ISSUE THREAD

**Issue by AsclepiusDoc** [eldariont/svim#26]
Hello SVIM,

I just have a quick question about the score each variant call and the ones used as a cut-off eg. q5 and q10. 

In the wiki it mentions:

`Since the publication of our manuscript, we changed the score formula to the formula described **here.** The current formula puts more emphasis on the number of supporting reads than on the other features.`

However, I don't see the formula used for scoring, am I missing something?

Kind Regards,

Alex Lim

**Comment by eldariont** [comment]
Hi Alex,

thanks for this good question. The formulation of this sentence in the wiki is indeed quite confusing. By "here" I was refering to the same paragraph where it says:
`The score is mainly based on the number of supporting reads. Additionally, the agreement between the supporting reads concerning the span and position of the SV is taken into account.`

I should probably include the exact formula in this paragraph to make it more clear how exactly the score is calculated. Until I have done that you can have a look at the function here: https://github.com/eldariont/svim/blob/master/src/svim/SVIM_clustering.py#L85

It takes as input: `cluster` (the list of reads supporting the variant), `std_span` (standard deviation of the spans), `std_pos` (standard deviation of the positions), `span` (average span), `type` (SV type).

Cheers
David

**Comment by eldariont** [comment]
Hi Alex,

I finally had time to add the score formula to the wiki: https://github.com/eldariont/svim/wiki/2.-Interpreting-the-output#how-is-the-score-defined-that-each-variant-call-receives.

Therefore, I'm closing this issue now but feel free to reopen if any questions remain.

Best,
David

**Comment by zuzanahalenkova** [comment]
Hello, 
I was wondering whether there isn't an error in the score computation formula in Wiki. The code at https://github.com/eldariont/svim/blob/master/src/svim/SVIM_clustering.py#L85 seems to take min(80, number_of_supporting_reads), while in Wiki, there is maximum from these two values.
Thanks!

**Comment by jakob-he** [comment]
Hi @zuzanahalenkova ,

thanks a lot for noticing this!
The correct formula is min(80, number_of_supporting_reads). I have changed the Wiki accordingly.

Best,
Jakob
