### ISSUE TITLE
Suggestion/Request: add to PyPI and/or bioconda

### ISSUE THREAD

**Issue by wdecoster** [eldariont/svim#3]
Hi,

Not that I had issues with installing svim, but especially for novice users adding your tool to PyPI and/or bioconda could make installation less painful. Simultaneously, it would make sure that your scripts are placed in $PATH

Please let me know if you need some help to figure this out!

Cheers,
Wouter

**Comment by stain** [comment]
pip: https://pypi.org/project/svim/
bioconda (in progress): bioconda/bioconda-recipes#12272

**Comment by wdecoster** [comment]
Great :)
