### ISSUE TITLE
[Feature request] Expose CLI for customizing batch size

### ISSUE THREAD

**Issue by SHuang-Broad** [eldariont/svim#32]
Right now SVIM seems to process in batch of 10K reads, and keep them in memory (from the log and memory footprint).

Would it be possible to expose an CLI allowing users to specify the batch size (bigger), hence speeding up the process?

Thanks!
Steve

**Comment by eldariont** [comment]
Hi Steve,

what you see in the logs are no batches but simply progress reports. SVIM iterates through the BAM file from start to end and stores all SV signatures in memory (https://github.com/eldariont/svim/blob/master/src/svim/SVIM_COLLECT.py#L127). Until now, I didn't find memory consumption to be a big problem.

The speed of SVIM is mainly limited by IO, i.e. reading the BAM file takes up the most time. The best way to speed up the process is to split up your BAM file by chromosome and process each chromosome with a separate instance of SVIM.

Best
David
