### ISSUE TITLE
raw reads or corrected reads ?

### ISSUE THREAD

**Issue by ptranvan** [eldariont/svim#35]
Hi !

Do you have any tips ? what should I use for the alignment, raw or corrected long reads ?

Cheers,

**Comment by eldariont** [comment]
Hi Patrick,

generally, fewer sequence errors lead to better SV calls. Therefore, I would probably use corrected reads. Keep in mind, though, that read correction can also introduce new errors into the reads, e.g. by over-correcting and removing heterozgous variants.

You can get a good feeling of your data by viewing read alignments in a genome browser. SVIM merely calls what is in the alignments so whichever alignments look better (or more correct) to you will probably also produce better results.

Cheers
David
