### ISSUE TITLE
Is SVIM suitable for detecting somatic SV?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [eldariont/svim#40]
Hi,
I am wondering that can I run SVIM for paired control-tumor sample, and obtain the somatic SV through the subtraction of normal sample and tumor sample?
Is SVIM designed for germline SV detection?

Thanks,
Charlie

**Comment by eldariont** [comment]
Hi Charlie,

yes, SVIM is designed for germline SV detection. But in principle your approach of subtracting the control SVs from the tumor SVs might work.

One problem might be the heterogeneity of the tumor. For filtering and genotyping germline SVs by the number of supporting reads one usually assumes that all reads come from the same genome. In a tumor, this assumption might be wrong when you have different subpopulations in your sample.

Another challenge is the subtraction. You could try a simple tool, such as [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR/wiki#consensus-calling-or-comparing-svs-across-samples), first. After merging the variants from control and tumor, you can filter for those that were called in the tumor only.

Please let me know if you have any other questions regarding SVIM.

Cheers
David
