### ISSUE TITLE
what is the recommended annotation tools after SV calling?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [eldariont/svim#42]
Hi,

I am wondering the recommended gene annotation tools after SV calling, to estimate the SV effect on human genes mutation.

**Comment by ebioman** [comment]
Not sure if there is the "one" tool, but [https://lbgi.fr/AnnotSV/](https://lbgi.fr/AnnotSV/) is pretty good IMHO

**Comment by eldariont** [comment]
Thanks @ebioman for the good suggestion. I don't have a lot of experience with annotation tools but AnnotSV looks very useful. Another recent tool designed for deletions and duplications is [ClassifyCNV](https://www.nature.com/articles/s41598-020-76425-3).
