### ISSUE TITLE
svim alignment error

### ISSUE THREAD

**Issue by lukaslee1127** [eldariont/svim#43]
I followed the evaluation step by step and i got the error at step 9 .
{
9. Run SVIM on BAM file with distance threshold=1.4 for signatures to be merged into clusters:
svim alignment --cluster_max_distance 1.4 svim_wd aln/hs37d5.all.querysorted.bam
}
I've got
svim alignment --cluster_max_distance 1.4 svim_wd aln/hs37d5.all.querysorted.bam
usage: svim alignment [-h] [--verbose] [--min_mapq MIN_MAPQ]
                      [--min_sv_size MIN_SV_SIZE] [--max_sv_size MAX_SV_SIZE]
                      [--segment_gap_tolerance SEGMENT_GAP_TOLERANCE]
                      [--segment_overlap_tolerance SEGMENT_OVERLAP_TOLERANCE]
                      [--partition_max_distance PARTITION_MAX_DISTANCE]
                      [--distance_normalizer DISTANCE_NORMALIZER]
                      [--cluster_max_distance CLUSTER_MAX_DISTANCE]
                      [--all_bnds]
                      [--del_ins_dup_max_distance DEL_INS_DUP_MAX_DISTANCE]
                      [--trans_sv_max_distance TRANS_SV_MAX_DISTANCE]
                      [--skip_genotyping] [--minimum_score MINIMUM_SCORE]
                      [--homozygous_threshold HOMOZYGOUS_THRESHOLD]
                      [--heterozygous_threshold HETEROZYGOUS_THRESHOLD]
                      [--minimum_depth MINIMUM_DEPTH] [--sample SAMPLE]
                      [--types TYPES] [--sequence_alleles]
                      [--insertion_sequences]
                      [--tandem_duplications_as_insertions]
                      [--interspersed_duplications_as_insertions]
                      [--read_names] [--zmws]
                      working_dir bam_file genome
svim alignment: error: the following arguments are required: genome

how do i handle it?

**Comment by eldariont** [comment]
Hi Donghyun,

thanks for your question. The evaluation guide you were using was unfortunately a bit outdated. Current versions of SVIM require at least three arguments:
- a working directory
- the input BAM file
- the reference genome

In the wiki guide, this last argument was missing and SVIM is complaining about that.

I now updated the guide so please check it out again: https://github.com/eldariont/svim/wiki/3.-Evaluation-on-HG002-with-GiaB-draft-truth-set

The following steps were changed:
- step 2 fetches the .tbi index for the truth set
- step 3 uses pip to install a more recent version of truvari
- step 8 merges the BAM files and does not sort by query name any more, the final file is indexed
- step 9 updates the call of SVIM
- step 10 updates the filtering
- step 11 updates the call of truvari
- step 12 updates the result parsing

Please let me know whether everything works now with the updated steps.

Cheers
David
