### ISSUE TITLE
The genotype of the variants.vcf file were ./.

### ISSUE THREAD

**Issue by fantasticair** [eldariont/svim#46]
Hello,
I used the `SVIM` to call the HiFi reads SV, in the result of variants.vcf file, which the `GT` was `./.`,  my command is :
```
SVIM/bin/svim alignment ./ ${BAM} ${Reference} --min_mapq 20 --min_sv_size 30 --max_sv_size 100000 --minimum_depth 3 --sample ${SampleName} --sequence_alleles --insertion_sequences
```

and I used the HiFi coverage is 20X.
Whether need to set some parameters?

Best wishes~

**Comment by eldariont** [comment]
Hi,

If I interpret your question correctly, you are asking why some calls in the output file lack a genotype (`./.`). SVIM is currently able to estimate genotypes for deletions, insertions, inversions and interspersed duplications (not for tandem duplications). Additionally, it requires a certain minimum number of reads to estimate the genotype. This minimum number can be configured with the `--minimum_depth` option and is 3 in your case. Furthermore, it requires calls to have a certain minimum score (configured with the `--minimum_score` option). That means that variants detected by less than 3 reads or with a score lower than 3 will not get a genotype.

Does this answer your question?

Cheers
David
