### ISSUE TITLE
Reversed start and end of BND

### ISSUE THREAD

**Issue by charliechen912ilovbash** [eldariont/svim#54]
If the start and end of two BND, i.e. translocation, are reversed, does it means they are actually the same translocation event?
E.g.
```
id            start                end
TRA-1:   chr1,         1,    chr2,   100
TRA-2:   chr2,   100,   chr1,         1  
```

**Comment by jakob-he** [comment]
Hi @charliechen912ilovbash 

Yes, in this case the two breakends represent the same translocation.
Since SVIM returns the breakend locations rather than just one translocation event, both breakends are reported.

Best,
Jakob
