### ISSUE TITLE
Reads supporting BND events

### ISSUE THREAD

**Issue by Akazhiel** [eldariont/svim#57]
Hello!

I've noticed when the SV is a BND event, all the `FORMAT` fields are reported as "missing", example `GT:DP:AD        ./.:.:.,.`.
I know tandem duplications are not genotyped as of yet, but I was expecting BND or Translocation events to be genotyped or at least report the `DP` and `AD` fields.

Is this a bug or SVIM does not report neither of these for BND events?

Best regards,

Jonatan

**Comment by Akazhiel** [comment]
Adding to this I've noticed that `DUP:TANDEM` don't have values for the `DP` and `AD` fields while the  `DUP:INT` variants do have them and are also genotyped. Is this behaviour intended or is it a bug?

Best regards,

Jonatan

**Comment by jakob-he** [comment]
Hi Jonatan,

thanks a lot for contacting us and sorry that I haven't been in touch yet!
At the moment SVIM does not support genotyping of `BNDs` or `DUP:TANDEM`. 
Currently, the process of counting the reference supporting reads - the basis of our genotyping - is only implemented for`DEL`,` INS`, `INV`, and `DUP:INT`. 
 So it is not possible to report `DP` or `AD` for the other two types but we will definitely keep this in mind for future updates!

Best,
Jakob
