### ISSUE TITLE
local variable 'end2' referenced before assignment

### ISSUE THREAD

**Issue by PhDstuff** [eldariont/svim#8]
Hi there, 
I am working with both ngmlr and minimap mapped reads and although the ngmlr files are easily accepted, I find that the minimap BAMs come against this error sometimes during the combine step, depending on the read data set and whether it is sorted by name or not...

> 2019-02-06`
>  10:38:27,976 [INFO   ]  ****************** STEP 3: COMBINE ******************
> 2019-02-06 10:38:27,976 [INFO   ]  Cluster translocation breakpoints..
> 2019-02-06 10:38:27,977 [INFO   ]  Combine inserted regions with translocation breakpoints..
> 2019-02-06 10:38:27,978 [INFO   ]  Create interspersed duplication candidates and flag cut&paste insertions..
> Traceback (most recent call last):
>   File "/usr/local/bin/svim", line 224, in <module>
>     sys.exit(main())
>   File "/usr/local/bin/svim", line 221, in main
>     combine_clusters(signature_clusters, options.working_dir, options, __version__, aln_file.references, aln_file.lengths, options.sample)
>   File "/usr/local/lib/python3.5/dist-packages/svim/SVIM_COMBINE.py", line 195, in combine_clusters
>     length2 = end2 - start2
> UnboundLocalError: local variable 'end2' referenced before assignment

Attached in the log file also.
Any clues?

Thanks

[SVIM_190206_103820.log](https://github.com/eldariont/svim/files/2835670/SVIM_190206_103820.log)

**Comment by eldariont** [comment]
Hi,

thanks for reporting this issue!
It is caused by a bug that only occurred when SVIM did not find any interspersed or tandem duplications in the reads. I fixed it with 499fa2d and hope that this resolves the problem.

Cheers
David

**Comment by PhDstuff** [comment]
That did the job!
Thanks for being so efficient David, really appreciated.

**Comment by eldariont** [comment]
You are welcome :)

**Comment by wdecoster** [comment]
If you could update the recipe on conda, well, that would be great :-)

(Just came across this issue myself)

**Comment by wdecoster** [comment]
Oh, and another suggestion: please make sure that the traceback on an error is also logged in the logfile. I ran a bunch of samples in parallel, and it was unclear why some didn't complete (due to the bug of this issue).

In my tools I solve this by catching the exception, logging it, raising it again:
```
def main():
    try:
        do_all_stuff()
    except Exception as e:
        logging.error(e, exc_info=True)
        raise
```

**Comment by eldariont** [comment]
Hi Wouter,
thanks for the good suggestion about the exception logging. I added this in 488b3b6 and drafted a new release (0.4.4). This should trigger the update of the conda recipe which will hopefully be online soon.
