### ISSUE TITLE
order of reads in bam file

### ISSUE THREAD

**Issue by wdecoster** [eldariont/svim#9]
I believe this part of your wiki is outdated (https://github.com/eldariont/svim/wiki#bam-input):

> Currently, read alignments need to be sorted by read name (samtools sort -n).

Same for the command line help information:

>  bam_file              SAM/BAM file with aligned long reads (should be
                        queryname-sorted with samtools sort -n)

In addition, the wiki contains `python svim.py` usage, which can probably be replaced by just `svim`

**Comment by eldariont** [comment]
Hi Wouter,
thanks for letting me know! Four eyes see more than two :)
I updated the wiki accordingly but left the command line help information which deliberately says that BAM files `should be queryname-sorted`. As now explained in the wiki results will be more accurate on queryname-sorted input. Therefore, it's `should` but not `must`.

**Comment by wdecoster** [comment]
Then I'd write "sorted, preferentially on queryname with samtools sort -n" ;-)

**Comment by eldariont** [comment]
Agreed :) I will push this change with one of the next commits.
